### ISSUE TITLE
Crash by Rocket creeper spinning animation

### ISSUE THREAD

**Issue by Xpart4real** [Daveyx0/PrimitiveMobs#125] opened 2018-10-09 18:38 UTC
i played this mod for a while now, and i didn't expect this bug to happend cause i never seen it or happend to me on 1.7.10, this bug on the 1.12.2 version btw

    i used to hit rocket creepers before i run from their explodes, but this happend, i came to one, he jumped high and fall with it's spinning animation, when he exploded, he didn't die, he was just floating and the spinning animation was still animating in place even after the explosion, after that, my game crashed, from that time whenever a rocket creeper comes close to me it still crashes because of its spinning animation problem after it's explode, the bug kept going, so i had no choice but to delete my saved world, and the bug was gone. from now i'm playing completly fine with the mod, but maybe it happens again by possible causes, i may not be the only one, so i'm asking u modders to fix this since it's just the beta versions. that's all from now. i wish u the best of luck 

NOTE: this is my first post ever on this webside so u can expect boring talks :(

         BYE.

**Comment by Xpart4real** [comment] 2018-10-09 18:39
oh and i don't have any mods installed just optifine

**Comment by Daveyx0** [comment] 2018-12-17 06:42
Thanks for reporting! Sorry for the late respomse. Wait, no other mods but optifine? Are you sure? Then I indeed need a crash report :)

**Comment by Daveyx0** [comment] 2018-12-27 13:58
Assuming this was caused by an older bug, which is fixed in the most recent version. Closing this.

**Closed by Daveyx0** 2018-12-27 13:58 UTC
Labels: bug
