### ISSUE TITLE
Experiencing crashes after any edits to loot tables

### ISSUE THREAD

**Issue by shencil** [Daveyx0/PrimitiveMobs#24] opened 2017-12-26 11:33 UTC
filch lizard specifically, not sure about the others.  happens after changing weight or after adding modded items

**Comment by Daveyx0** [comment] 2017-12-27 15:28
Cannot reproduce. Could you post the relevant part of primitivemobs.cfg? 

Also, thanks for using this feature and testing it 👍

**Comment by Daveyx0** [comment] 2017-12-31 13:12
Seeing as I still cannot reproduce; I will close this for now. Re-open when encountered again, but please add a crash report.

**Closed by Daveyx0** 2017-12-31 13:12 UTC
