### ISSUE TITLE
[Bug] Spawner Error Spamming Console

### ISSUE THREAD

**Issue by ddelaparte** [Daveyx0/PrimitiveMobs#41] opened 2018-01-16 23:00 UTC
Receiving the following error, which spams the console. Eventually I get a ticking entity crash which mentions no specific entity or mod, however I cannot load the affected world until removing this mod.

`[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: java.lang.reflect.InvocationTargetException
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at sun.reflect.GeneratedConstructorAccessor194.newInstance(Unknown Source)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner.doCustomSpawning(PrimitiveMobsWorldSpawner.java:113)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at net.daveyx0.primitivemobs.event.PrimitiveMobsSpawnerEventHandler.onWorldTickEvent(PrimitiveMobsSpawnerEventHandler.java:34)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_649_PrimitiveMobsSpawnerEventHandler_onWorldTickEvent_WorldTickEvent.invoke(.dynamic)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:285)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[17:50:19] [Server thread/INFO] [STDERR]: [net.daveyx0.primitivemobs.spawn.PrimitiveMobsWorldSpawner:doCustomSpawning:117]: 	at java.lang.Thread.run(Unknown Source)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.IllegalArgumentException: Duplicate id value for 16!
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.network.datasync.EntityDataManager.func_187214_a(EntityDataManager.java:113)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.daveyx0.primitivemobs.entity.monster.EntityPrimitiveSpider.func_70088_a(EntityPrimitiveSpider.java:78)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.daveyx0.primitivemobs.entity.monster.EntityMotherSpider.func_70088_a(EntityMotherSpider.java:53)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.entity.Entity.<init>(Entity.java:217)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:163)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:120)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.entity.EntityCreature.<init>(SourceFile:21)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.entity.monster.EntityMob.<init>(EntityMob.java:26)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.daveyx0.primitivemobs.entity.monster.EntityPrimitiveTameableMob.<init>(EntityPrimitiveTameableMob.java:38)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.daveyx0.primitivemobs.entity.monster.EntityPrimitiveSpider.<init>(EntityPrimitiveSpider.java:50)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.daveyx0.primitivemobs.entity.monster.EntityMotherSpider.<init>(EntityMotherSpider.java:47)
[17:50:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 14 more`

**Comment by Daveyx0** [comment] 2018-01-16 23:15
Thanks for reporting. Could you possibly put the entire log of that session up for download here? Im curious about this one.

**Comment by ddelaparte** [comment] 2018-01-17 00:37
https://file.io/tIUCKa

**Comment by ddelaparte** [comment] 2018-01-17 00:38
I haven't reproduced the ticking entity crash since last removing and replacing the mod to fix a world, but above shows the console spam at least.

**Comment by Daveyx0** [comment] 2018-01-17 11:21
The log file seems to have expired. I kinda see what is happening here; however I'm confused how this is happening when no new SpawnList entries have been made by me.

**Comment by IIMarabarII** [comment] 2018-01-19 06:38
I got a similar ticking entity problem and it seems to be revolving around the Skeleton Warrior.  It seems to only do this when the skeleton is returning to an idle animation since it only crashes when I walk far enough away from one or I die to one.  Also, I would like to add that the config file that enables or disables mobs apparently does not work as intended, at least for the Skeleton Warrior as I disabled the mob both on my client and on the server but it still spawn naturally.  The only difference is that it is loaded without any skins and a hit box making it an invincible, invisible, server crashing beast.

If you want the logs or crash reports, I will be happy to post them for you.

**Comment by Daveyx0** [comment] 2018-01-19 10:28
Yes I would like the logs and reports very much. Also a question: did you restart everything after disabling the mobs and are you using the latest version? After I get the logs I will do some more tests, but it really should never be added to the spawn list. Anyway the Skeleton Warrior ticking entity crash is actually way more interesting atm. Thanks for reporting.

**Comment by IIMarabarII** [comment] 2018-01-20 05:15
I discovered the version I had downloaded was post 1.1 beta and pre 1.1.4 beta from what I could find.  I just downloaded the most recent version you released, so I'll test if the ticking crash with the Skeleton Warrior still persists with this version.

**Comment by IIMarabarII** [comment] 2018-01-20 18:56
Ah, ok.  The ticking entity crash with the Skeleton Warrior seems to have been fixed in the most recent update.  My bad.  XD

**Comment by Daveyx0** [comment] 2018-01-20 22:59
Ok thanks for testing Marabar. Still need to take a look at the problem described by ddelaparte tho.

**Comment by Los2tale** [comment] 2018-01-24 10:54
got this spam too
https://pastebin.com/K0tMXLFp

**Comment by Daveyx0** [comment] 2018-02-23 21:03
Still need to find where this one originates... at least it doesnt crash everything, but still. It appears to be related to the Mother Spider somehow.

**Comment by Daveyx0** [comment] 2018-09-08 14:11
Should be fixed next update

**Closed by Daveyx0** 2018-09-08 14:11 UTC
