### ISSUE TITLE
exception while adding particle

### ISSUE THREAD

**Issue by kreezxil** [Daveyx0/PrimitiveMobs#86] opened 2018-05-06 14:58 UTC
https://pastebin.com/mqBih9zt

**Comment by Daveyx0** [comment] 2018-06-19 05:58
Will take a look. Thanks! Sorry for the late response

**Comment by Adarcer** [comment] 2018-07-01 17:50
Did not crash game but here is another particle exception .. possibly caused by creeper explosion because there was a explosion then the warning. I turned off creepers so that may help.

https://paste.dimdev.org/xutugufojo.mccrash

**Comment by jaz000** [comment] 2018-07-21 11:36
We get this too - kicks people out of the game
lots of other mods involved in case of interaction
https://pastebin.com/FUmLnUCy
Vanilla fix catches it (if you use that mod as well)

**Comment by Daveyx0** [comment] 2018-09-08 14:50
Fixed in next version

**Closed by Daveyx0** 2018-09-08 14:50 UTC
