### ISSUE TITLE
Strange mob spawning changes with new alpha version. For 1.12.2

### ISSUE THREAD

**Issue by SirAron111** [Daveyx0/PrimitiveMobs#142] opened 2018-12-17 21:32 UTC
It somehow messes with the mobs spawning in general. I am running the modpack “Dimension Zero” that relies on the increased amount of mobs that can spawn and increasing difficulty. (Scaling health, increase mobs, rough mobs 2 etc.) But since updating your mod (deleted the old config to let the new one generate) the amount of mobs that spawn is drastically decreases normally there where hordes of monsters every night now it’s like 1 zombie and 1 haunted tool or so making it way to easy.

Does the new version ignore normal spawn rules? Like the 110% extra spawn from increased mobs or he modded mobs from other mods like grimoir of gaia? Since these don’t get spawned in the same amount anymore to. Also I can’t find a way to set spawn  chances for the primitive mobs only extra rarity and max spawn amount so I can’t manually pump spawn rates up only decrease them.
I know that the multy mob core configs have a lot of extra configs but that also didn’t help.

Version: primitivemobs-1.2-alpha.jar
Forge: 14.23.5.2796
MC: 1.12.2

**Comment by Daveyx0** [comment] 2018-12-17 21:39
My mod ultimately SHOULD not change any of these spawns.... however I have heard complaints like this in the past and am really starting to wonder why the mod changes other mod spawn behaviors. I will investigate, SirAron. Thanks!

**Comment by SirAron111** [comment] 2018-12-17 22:00
Thank you for the fast replay XD it normally takes weeks to even get answers from mod makes.
Really hope it works out.

Feel free to test your alpha with my Modpack to find incompatibilities with other mods or compare the mob spawns (version 4.9 runs the non alpha version and the mob spawns work fine there) if that helps. It starts up fine with the alpha version of your mod just in game there are these strange issues as if any other spawning change gets overwritten (Modded mobs still spawn and vanilla to just not with the change in amount and ai changes they should due to the other Mods). Only if that helps i am not good with modding so i dont know XD

**Comment by SirAron111** [comment] 2018-12-23 11:43
I think I found something related to the spawning behavior.

If I set the multy mob core config to have the max allowed spawns for certain mob types from the standard 2 or 6 to something bigger like 100 it actually allows more spawns to happen could it be that this config messes with spawn caps in a way that confuses other mods that mess with spawn caps etc.

Also adding some of the normal mobs from vanilla or other mods to the spawn on specific blocks list like grass etc makes insane amounts of these mobs spawn (sometimes not always really strange) (too much even for my taste).

Oh! and lastly the grove spirit is constantly black and doesn’t change his color like the camelion in the.
That’s all I figured out for now. Will have to revert to the previous beta version for now so I can prepare for a pack update!

**Comment by Daveyx0** [comment] 2018-12-23 11:50
Thanks for the info, SirAron. It's a tricky one. In my personal modpack the amount of mobs is OK, but not a lot either. Will have to continue debugging and see if something is blocking mobs from spawning. And the block thing is interesting as well; seeing as that only should happen when you clearly set the overrideSpawnChecks option.

**Comment by SirAron111** [comment] 2018-12-23 11:50
Also it is really troublesome that there is no config option to configure the actual spawn rarity of the mobs them self to make them spawn more than intended. I can only make them rarer with the multy mob core but not increase the spawn rate like I could In the previous config. There should be a base spawn rate config.

**Comment by Daveyx0** [comment] 2018-12-23 11:56
Increase spawn rate has always been the max amount of mobs that can spawn of that type, it was just named differently. The game checks every X game ticks to perform a spawn and I cannot actually set that per mob. I CAN however make a config option for that general spawn frequency and will look into that.

**Comment by Daveyx0** [comment] 2018-12-23 18:45
Also have a small question SirAron, have you been making new worlds to test this by chance?

**Comment by SirAron111** [comment] 2018-12-23 20:13
tested it in an existing world (copie) and made some new worlds (around 8 as i was also testing alot of other stuff) and there i noticed the drastic decrease in mobs (now that i reverted back in preperation for updating the pack after cristmas there are again the intended many mobs talking about a 20-25 mobs more around the base)

**Comment by Daveyx0** [comment] 2018-12-23 21:10
I think I might have found the issue here. :O although I dont know how my old version did not run into this issue... What happened is that Minecraft simply detects if a mob is of a certain type and, if so, adds it to a number. That number is used to restrict general mob spawns. Because most of my mobs derive from EntityMob and therefore IMob, they are seen as mobs that are spawned by the world spawner. Now I made sure they are NEVER seen as a specific creature type used in spawning. We'll see if this fixes things.

**Comment by Daveyx0** [comment] 2018-12-23 21:13
The fact that there are 5 new mobs that now try to spawn might have made it so the number decreased for you, as well as the fact that I rebalanced stuff.

**Comment by SirAron111** [comment] 2018-12-23 22:05
That could be it. I think your previous mod could have run into the same problem that’s actually the reason why I installed the increase mobs mod so I could increase the amount and cap of spawned mobs that fixed it in the last version (last version sometimes made nor vanilla mobs spawn if I didn’t have that mod installed) but in this alpha version even setting it to 20 % more spawns from 10% extra I had before didn’t help much (did help a little thought but I couldn’t go higher). If that is the problem that would be awesome if it fixes it! GJ

**Comment by SirAron111** [comment] 2018-12-24 21:20
I updated to the new multy mob core and primitive mobs that got released just now and deleted the old config for both so a new one could generate for both. Changed nothing this is the result.

Spirits still go black

![2018-12-24_20 51 20](https://user-images.githubusercontent.com/39855956/50406659-0ed26080-07c9-11e9-87cb-3a48e5f7a92c.png)
![2018-12-24_20 50 30](https://user-images.githubusercontent.com/39855956/50406660-0f6af700-07c9-11e9-8162-3a98bc790abb.png)

Mobs are still scarce in over world and cave layer (it’s not that nothing spawns it just that it’s a lot fewer mobs in compression to the way they did before in my pack will add pictures of before below)

![2018-12-24_22 01 05](https://user-images.githubusercontent.com/39855956/50406669-2578b780-07c9-11e9-9211-83f0ebf1d688.png)
![2018-12-24_22 08 24](https://user-images.githubusercontent.com/39855956/50406670-26114e00-07c9-11e9-8f9b-8e471befc39f.png)

To compare this is what the night looks like before updating (with the 1.16 beta version of the primitive mobs mod)

![2018-12-24_21 48 45](https://user-images.githubusercontent.com/39855956/50406676-3fb29580-07c9-11e9-9d8a-e99280c878ec.png)
![2018-12-24_21 48 56](https://user-images.githubusercontent.com/39855956/50406677-404b2c00-07c9-11e9-908d-b7eb7c0ad246.png)

Maybe it’s just me or I imagine things I don’t know sry

**Comment by Daveyx0** [comment] 2018-12-24 21:34
Ok so Im officially stumped then. Going to need more people giving info on this... can I perhaps have your mod list foe the grovsprite issue? Cause for me it was caused by ctm and that should be fixed... thanks!

**Comment by Daveyx0** [comment] 2018-12-24 21:35
Sorry for the inconvenience SirAron, I dont know whats different from the previous version in essence....

**Comment by SirAron111** [comment] 2018-12-24 21:49
Oh don’t be sorry I am sorry that I am causing you headaches.

It’s not that much of a problem for me I can just decide to not update to the new version until I or you or someone else finds a fix or workaround. I am just reporting what I find in hope it helps XD.

I remember causing another mod author a big headache for 2 or 3 weeks until we found the problem and it was literally just one small line of code not being done correctly because it had a (:) instead of a (;) in it.

O and for the mod list:

https://minecraft.curseforge.com/projects/dimension-zero

It’s at the bottom of the page if that helps.

**Comment by SirAron111** [comment] 2018-12-24 22:00
As for the spirits and chameleons being black I just tested it with and without Optifine installed they are black in both ways so it’s not Optifine. (Optifine is a recommended mod for my pack but not part of the pack but I personally use it) just to make sure.

**Comment by Daveyx0** [comment] 2018-12-24 23:13
Yeh I also tried Optifine. Thats a big mod list... oof. It sucks cause the black mobs is likely caused by some "core" mod like ConnectedTextureMod which caused the problem before... its funny cause the sprite does seem to work like normal from your screens, just the color is bugged. Could you test without the resourcepack for me? I tried with faithful and that still worked here :( 
And for the spawn issue, could you remove primitivemobs and multimob completely and check spawns then? And then only add multimob and check again? I know Im asking a lot but Im definitely stumped xD it could be some weird mishmash of mods issue.... cheers!

**Comment by Daveyx0** [comment] 2019-01-04 23:14
After many more struggles, I might have the solution ready for the next update.

**Comment by SirAron111** [comment] 2019-01-05 00:31
I found a small work around that I am using for now (making all mobs have one extra spawn check not -1 and I also pumped up the amount of allowed mobs to like 20 instead of 8 for the tools and the spawn frequency to 30 instead of 40 for the tick setting. This must be terrible on performance and servers XD but it does work for now).

I can’t wait to see if what you did works.

**Comment by Daveyx0** [comment] 2019-01-06 14:39
Newest MultiMob and PrimitiveMobs has the new system. Or basically the old system. It now uses the vanilla world spawner and some custom creatureTypes. Minecraft uses the creatureTypes to limit spawns which is why you increase them through the IncreaseMobs mod. I added my own which SHOULD work seperately with their own limits (currently set to about half of normal MONSTERS). To increase spawns dramatically like you want; simply use the AdditionalSpawningOptions setup by MultiMob. Enable it, set the tick delay to 2-3 (minecraft also calls it quite often so it shouldn't be too big of an issue, otherwise increase it) and increase the limits of the creature types which often speak for themselves. Then you can whitelist the dimensions if needed. (I use the additional spawner in my own setup as well with about an increased MONSTER limit of 150 and MULTIMOB_MONSTER limit of 30 and it works quite well. I find I don't want to enable it in the Nether to avoid craziness)

Really hope it helps; otherwise you might have too many systems colliding causing issues with your spawn setup. I find that when I do not add the additional spawner from multimob I also don't get a lot of mobs, but this is simply inherent to having a load of new creatures that confuse the system. Try it out and we will see :P

**Comment by SirAron111** [comment] 2019-01-06 16:57
Well as of now all these changes work fine I can make mobs spawn in masses now and even set limits that’s nice it even handles modded mobs from other sources. All that’s left now is for me to find the right setting (to prevent millions of chameleons and grove spirits spawning or the like XD) don’t know if I even need increase mobs anymore.
But I crashed once when changing in game configs here is the report for that

https://pastebin.com/MhcCiUCG

**Comment by SirAron111** [comment] 2019-01-06 19:13
One last question I have before you can close this.

The spawn caps for the additional spawns I set them to like 80-120
Do they only affect extra spawned mobs or all mobs in general and how does this cap affect servers where 2 or more players are a t different places. Does one player get all the spawns and the next one that joins doesn’t get any mobs if he is further away from the other one who capped out or is it around/ per player is some sense

**Comment by Daveyx0** [comment] 2019-01-06 19:19
Yeh that crash is definitely cause the tick rate was set to 0, nice catch! Will fix. As for the amount of spawns, it should be reliant on the amount of chunks that are available to spawn. If you have 2 players; it should increase the amount that is allowed according to the logic. These spawn caps get added to the vanilla one (if you chose Vanilla Monster for example), so if you choose 80 it will be added to the default which is 70 so 150 mobs in the 17 x 17 loaded chunks for each player max (at least who use that type). Most mods will use the vanilla Monster type to add spawns while the Primitive mobs use the MultiMob specific ones. MultiMob Monster is by default a limit of 35 mobs. Also as you might already noticed; by default it only works on the overworld but you can change that. If you dont want more GroveSprites you can just make that MultiMob Passive on 0 and it will go back to default (just dont make the tick delay 0 xD)

Really happy it works now though!!

**Comment by Daveyx0** [comment] 2019-01-06 19:51
Technically you can get rid of IncreaseMobs if you use this system btw; but that's up to you. Enjoy! I pray for your players xD

**Closed** 2019-01-10 20:18 UTC
Labels: bug
