### ISSUE TITLE
After Loading up a game it instantly crashes on me and it does it again and again.

### ISSUE THREAD

**Issue by Justb123** [Daveyx0/PrimitiveMobs#62] opened 2018-03-07 03:21 UTC
After loading up any save game it crashes on me. I put 
Show the animated overlay on summons =false     that to false and still does the same thing
PLEASE HELP!!!

**Comment by NotAVerb** [comment] 2018-03-09 19:06
Do you have a crash log?
https://gist.github.com/

**Comment by Justb123** [comment] 2018-03-10 07:54
Sorry, I don't know how to find the crash log. Could you tell me? Thank You.

**Comment by kreezxil** [comment] 2018-03-10 14:52
If you've used the TwitchApp to make or install your pack. Go to it and right click on the profile icon for the pack and choose view profile. In the upper right of the next screen there is "..." 3 dots, click that and choose "open folder", the crash report will be listed in the **crash reports** folder. You will want to put the contents of the crash report that pertains to your crash in https://gist.github.com or anyother pasting service and then supply the resulting url.

**Comment by Justb123** [comment] 2018-03-10 19:48
I don't use twitch app to get mods I use curseforge and than download the mod into java and put in %appdata% than .minecraft after then I put it in mods.

**Comment by kreezxil** [comment] 2018-03-10 21:04
even so, in the .minecraft folder, there will be a folder called "crash reports", enter it and you put the contents of the latest one on a pasting service and provide the link here.

**Comment by Justb123** [comment] 2018-03-14 03:35
sorry just finished camp ok thanks

**Comment by Justb123** [comment] 2018-03-14 03:37
https://gist.github.com/Justb123/18bdef18ef6700327492228e2206af3e#file-gistfile1-txt

**Comment by Justb123** [comment] 2018-03-14 03:39
Here is the crash report.
thanks for the help! 👍

**Comment by kreezxil** [comment] 2018-03-14 10:57
I'm not sure why I decided to be Santa's Little Helper in this thread, but looking at your crash report which is incomplete because you were supposed to copy all of it, not some of it. Next time after you enter the file click **Edit**->**Select All** and then **Edit**->**Copy** or with key combos do **ctrl+a** then **ctrl+c**, then in the gist section where you paste, you can right click paste. 

Anyhow the first line of that crash trace says the Mob Battle Mod is at fault, not Primitive Mobs. Therefore you need to post this issue on https://github.com/Flemmli97/MobBattle/issues

**Comment by Justb123** [comment] 2018-03-16 02:26
Here is the full i think

**Comment by Justb123** [comment] 2018-03-16 02:26
https://gist.github.com/Justb123/3fd940bfb8aef0c275f9b0bb3755b447

**Comment by Justb123** [comment] 2018-03-16 02:28
that is what it has got

**Comment by Justb123** [comment] 2018-03-16 02:59
When i removed the mob battles it still crashes

**Comment by kreezxil** [comment] 2018-03-16 12:54
now send him the updated crash report

**Comment by Daveyx0** [comment] 2018-03-16 18:27
Thanks Kreezxil. Did not have time to attend this. Please send the new crash report Justb123 :)

**Comment by Justb123** [comment] 2018-03-16 21:24
I unsubscribed to the thread I think

**Comment by Justb123** [comment] 2018-03-16 21:25
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ItemPatchingLoader (ItemPhysic Full 1.4.7 mc1.12.jar)
  CreativePatchingLoader (CreativeCore v1.8.5 mc1.12.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 8/11/17 9:38 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lucky Block (lucky)
Caused by: java.lang.ClassNotFoundException: mod.lucky.Lucky
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:533)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 42 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 139833456 bytes (133 MB) / 341049344 bytes (325 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar) 
	UC	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar) 
	UC	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UC	itemphysic{1.4.0} [ItemPhysic] (minecraft.jar) 
	UC	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar) 
	UC	dmonsters{1.53} [Deadly Monsters] (1.12_deadly_monsters_1.53.jar) 
	UC	adminweapons{3.4} [Admin Weapons] (adminweapons-v3.4-mc1.12.jar) 
	UC	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.8.5 mc1.12.jar) 
	UC	deathquotes{1.2.0} [Death Quotes] (DeathQuotes-1.2.0-mc1.12-forge.jar) 
	UC	jei{4.7.4.80} [Just Enough Items] (jei_1.12-4.7.4.80.jar) 
	UC	jaff{1.7_for_1.12} [Just a Few Fish] (JustAFewFish-1.7_for_1.12.jar) 
	UE	lucky{7.5.0} [Lucky Block] (lucky) 
	UC	metamorph{1.1.3} [Metamorph] (metamorph-1.1.3-1.12 (1).jar) 
	UC	mobbattle{1.9.0[1.12]} [Mob Battle Mod] (Mob Battle Mod 1.9.0 [1.12].jar) 
	UC	mobends{0.24} [Mo' Bends] (mobends-0.24_for_MC-1.12.jar) 
	UC	nex{2.1.11.12} [NetherEx] (NetherEx-1.12-2.1.11.12.jar) 
	Loaded coremods (and transformers): 
ItemPatchingLoader (ItemPhysic Full 1.4.7 mc1.12.jar)
  com.creativemd.itemphysic.ItemTransformer
CreativePatchingLoader (CreativeCore v1.8.5 mc1.12.jar)
  com.creativemd.creativecore.core.CreativeCoreTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 515'

**Comment by Justb123** [comment] 2018-03-16 21:27
https://gist.github.com/Justb123/5ab8f776458ee2f7353f569b5af4d0f7

**Comment by Justb123** [comment] 2018-03-16 21:27
Here are the crash reports

**Comment by Daveyx0** [comment] 2018-03-24 16:09
That seems to be a Lucky Block issue. Beginning to doubt this is a Primitive Mobs issue. It's been a while, were you able to fix it?

**Comment by Justb123** [comment] 2018-03-26 08:00
i will take out lucky blocks and mob battles and see if it will work i will get back to you soon

**Comment by Justb123** [comment] 2018-03-27 05:24
Still doesn't work

**Comment by Justb123** [comment] 2018-03-27 05:25
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ItemPatchingLoader (ItemPhysic Full 1.4.7 mc1.12.jar)
  CreativePatchingLoader (CreativeCore v1.8.5 mc1.12.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 8/9/17 5:47 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mob Battle Mod (mobbattle)
Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/common/event/FMLInitializationEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.getDeclaredMethods(Class.java:1967)
	at net.minecraftforge.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:403)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:598)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.event.FMLInitializationEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 153271360 bytes (146 MB) / 331796480 bytes (316 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar) 
	UC	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar) 
	UC	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UC	itemphysic{1.4.0} [ItemPhysic] (minecraft.jar) 
	UC	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar) 
	UC	dmonsters{1.53} [Deadly Monsters] (1.12_deadly_monsters_1.53.jar) 
	UC	adminweapons{3.4} [Admin Weapons] (adminweapons-v3.4-mc1.12.jar) 
	UC	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.8.5 mc1.12.jar) 
	UC	deathquotes{1.2.0} [Death Quotes] (DeathQuotes-1.2.0-mc1.12-forge.jar) 
	UC	jei{4.7.4.80} [Just Enough Items] (jei_1.12-4.7.4.80.jar) 
	UC	jaff{1.7_for_1.12} [Just a Few Fish] (JustAFewFish-1.7_for_1.12.jar) 
	UE	mobbattle{1.9.0[1.12]} [Mob Battle Mod] (Mob Battle Mod 1.9.0 [1.12].jar) 
	UC	mobends{0.24} [Mo' Bends] (mobends-0.24_for_MC-1.12.jar) 
	UC	nex{2.1.11.12} [NetherEx] (NetherEx-1.12-2.1.11.12.jar) 
	Loaded coremods (and transformers): 
ItemPatchingLoader (ItemPhysic Full 1.4.7 mc1.12.jar)
  com.creativemd.itemphysic.ItemTransformer
CreativePatchingLoader (CreativeCore v1.8.5 mc1.12.jar)
  com.creativemd.creativecore.core.CreativeCoreTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 515'

**Comment by Justb123** [comment] 2018-03-27 05:26
https://gist.github.com/Justb123/98a177a452cef738664679308b6bf43a

**Comment by Justb123** [comment] 2018-03-27 05:26
Here is the new crash reports for me taking out mob battles and lucky blocks

**Comment by Daveyx0** [comment] 2018-03-27 07:55
That still somehow seems to be a mob battle issue. Are you sure you took it out? At this point it might be better for you to just start over with installing mods and make sure nothing crashes, then leave put what does. I really doubt this is a Primitive Mobs issue.

**Comment by Justb123** [comment] 2018-03-28 06:18
: |

**Comment by Justb123** [comment] 2018-03-28 06:21
I will take out primitive mobs and see if Minecraft still works and if not I will send a crash report to you to tell me what is the problem if it works I will just not use primitive mobs. Thank you for helping so much with this I really appreciate it.

**Comment by Justb123** [comment] 2018-03-28 06:28
I don't know how to restart the progress I have made doing the forge and my mods

**Comment by Daveyx0** [comment] 2018-09-08 14:12
I assume this was caused by that other mod and will close it on my end.

**Closed by Daveyx0** 2018-09-08 14:12 UTC
