### ISSUE TITLE
Mobs not being disabled.

### ISSUE THREAD

**Issue by vivagabe** [Daveyx0/PrimitiveMobs#20] opened 2017-12-04 05:12 UTC
Im using the latest version and I've disabled the cute grove sprites.  The problem is, i can hear their adorable baby babbling so i know theyre spawning.  Not sure about the other mobs ive disabled.

**Comment by belathus** [comment] 2017-12-05 05:52
Yeah, I've disabled the festive creeper and set their spawn rate to zero, but I just had something invisible running through the base tossing TNT at us.

**Comment by Daveyx0** [comment] 2017-12-05 18:27
Even with their spawn rate to 0? That's odd. Will fix asap.

**Comment by TimGoll** [comment] 2017-12-10 10:53
I'm having the same issue, reported it at the wrong place:
https://github.com/Daveyx0/Primitive-Mobs-Mod/issues/3

**Comment by katubug** [comment] 2017-12-18 18:11
Server owner here, we're having the same problem with the invisible TNT throwing even though Festive Creepers are disabled.

**Comment by katubug** [comment] 2017-12-19 17:21
Ah okay, I might have figured out the issue, for us at least. We didn't change the spawn rate to 0 because we assumed that simply setting Festive Creeper to "false" would do the trick. I now have it set to false, AND a spawn rate of 0, and we haven't seen one since.

I suspect my mistake will be a common one, though. If you need to disable a mob twice in the config, it would be nice if the documentation told you so. Thank you for your hard work!

**Comment by Vazkii** [comment] 2017-12-19 18:12
It's not your problem. Disabling the mob should also prevent it from
spawning. There's something weird going on here and we don't really know
why.

**Comment by TimGoll** [comment] 2017-12-19 18:14
@katubug That might be possible. Are you sure?

**Comment by TimGoll** [comment] 2017-12-22 20:32
Okay. Setting spawn to 0 and disabling them does not prevent mobs from spawning
@katubug is wrong

**Comment by katubug** [comment] 2017-12-22 20:51
For the record, I never said definitively that that was the case. I said we
hadn't seen one since, not that I was sure they were disabled.

One of my players reported that she'd had TNT thrown at her after we made
the config changes, but I wanted to be sure that it wasn't on our end
(because we'd had to restore the server from a backup) before I reported it
to you.

I did check our config though, and it had them disabled and the spawn rate
to 0.

**Comment by TimGoll** [comment] 2017-12-22 20:52
I'm sorry. I did not want to offend you!
Just wanted to report it :)

**Comment by katubug** [comment] 2017-12-22 20:55
It's not a problem, I just wanted to clarify that I hadn't confirmed it was
fixed. :) And it was a good reminder for me to report my player's findings.
If there is anything I can do to help (not sure if logs or anything would
be useful), let me know.

**Comment by Daveyx0** [comment] 2017-12-23 10:45
Sorry for the delayed response; been working on some new content. Although I'm confused why mobs would even be added to the spawn list after being disabled; I can always make a work around., which I will. Thanks for the reporting, peeps.

**Comment by Daveyx0** [comment] 2017-12-31 13:09
This should finally be fixed in 1.1.4 which will be processed soon.

**Closed by Daveyx0** 2017-12-31 13:09 UTC

**Comment by katubug** [comment] 2017-12-31 17:08
Awesome, thank you for all your hard work!
